blog/main/urls.py
from flask import render_template, Blueprint, request
# from blog import Post
# from blog import db
from blog.models import Post
main = Blueprint('main', __name__)

@main.route('/', methods=['GET'])
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_created.desc())\
    .paginate(page=page, per_page=3) # displaying the posts in descending order
    return render_template('blog/home.html', posts=posts)

blog/posts/urls.py
from flask import render_template, url_for, request, redirect, flash, abort, Blueprint
from blog import db
from blog.models import Post, User
from flask_login import login_required, current_user
from blog.posts.forms import PostForm

posts = Blueprint('posts', __name__)

@posts.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('You have created a new post', category='success')
        return redirect(url_for('main.home'))
    return render_template('blog/create.html',title='New Post', legend='New Post', form=form)

@posts.route('/detail/<int:id>', methods=['GET'])
def detail(id):
    post = Post.query.get(id)
    return render_template('blog/detail.html', title=post.title, post=post)



@posts.route('/detail/<int:id>/update', methods=['GET', 'POST'])
@login_required
def update(id):
    post = Post.query.get(id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('You have updated the post!', category='success')
        return redirect(url_for('posts.detail', id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('blog/create.html', title='Update Post', post=post.id, legend='Upadet Post', form=form)

@posts.route('/detail/<int:id>/delete', methods=['GET', 'POST'])
@login_required
def delete(id):
    post = Post.query.get(id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('You have deleted the post!', category='success')
    return redirect(url_for('main.home'))


# Assignment
# In this view we are going to write a logic that when users
# click on Author's name will take them to that Author's entire posts page.
# 1- Create a simple function or route that does these logics:
@posts.route('/user/posts/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    # a) Filter User by its username.
    user = User.query.filter_by(username=username).first()
    # b) Filter Post by its Author
    posts = Post.query.filter_by(author=user)\
    .order_by(Post.date_created.desc())\
    .paginate(page=page, per_page=3)
    # c) Render template that displays specific Author's posts.
    return render_template('blog/user_posts.html', title='user posts', user=user, posts=posts)
# 2- From home page where all posts are displaying, add a url link that leads to that Author's posts page!. 

blog/templates/blog/account.html
{% extends 'base.html' %}

{% block content %}
<div class="row my-2">
    <div class="col-md-6">
        <h4 class="py-2"><strong>My Profile</strong></h4>
        <ul class="list-unstyled grid">
            <div>
                <img src="{{ image_file }}" class="img-fluid rounded-circle img" alt="" srcset="">

            </div>
            <div class="items mx-1 mt-2">
                <li>Username: {{ current_user.username}}</li>
                <li>Email: {{ current_user.email}}</li>
                <li>Date Joined: {{ current_user.date_joined.strftime('%Y-%m-%d') }}</li>
            </div>
        </ul>
        <div>
            <h4 class="py-2 text-uppercase">Update My Profile</h4>
            <form action="" method="POST">
                {{ form.hidden_tag()}}
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.img.label(class="form-control-label") }}
                    {% if form.img.errors %}
                    {% for error in form.img.errors %}
                    {{ form.img }}
                    <span class="text-danger">{{ error }}</span>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="form-group d-grid mt-1">
                    {{ form.submit(class='btn btn-primary text-uppercase')}}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

blog/templates/blog/create.html
{% extends "base.html" %}
{% block content %}
<div class="row my-2">
    <div class="col-md-6">
        <h4>{{ legend }}</h4>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo id facere culpa eum rem amet a recusandae
            et eos accusantium ex quae, dolores repellendus officiis! Unde molestias provident iste! Quis?</p>
        <form method="POST">
            {{ form.hidden_tag()}}
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                {{ form.title(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                {{ form.content(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.content.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group d-grid mt-1">
                {{ form.submit(class='btn btn-primary text-upper')}}
            </div>
        </form>
    </div>
</div>
{% endblock content %}

blog/templates/blog/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="row my-2">
    <div class="col-md-8">
        <a href="/" class="btn btn-secondary mb-3">&larr;back</a>
        <ul class="list-unstyled grid">
            <div>
                <img src="{{ url_for('static', filename='images/' + post.author.image)}}" class="img"
                    alt="{{ post.title }}">
            </div>
            <div class="items mx-1 mt-2">
                <li>Author: {{ post.author.username }}</li>
                <li>Date Posted: {{ post.date_created.strftime('%Y-%m-%d') }}</li>
                {% if post.author == current_user %}
                <a href="{{ url_for('posts.update', id=post.id)}}" class="btn btn-secondary">Update</a>
                <!-- Button trigger modal -->
                <a href="{{url_for('posts.delete', id=post.id)}}" type="button" class="btn btn-danger"
                    data-bs-toggle="modal" data-bs-target="#deleteModal">
                    Delete
                </a>
                {% endif %}
                <h6>{{ post.title }}</h6>
                <p>{{ post.content }}</p>
            </div>
        </ul>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Are you sure deleting {{ post.title }}?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-footer">
                <form action="{{ url_for('posts.delete', id=post.id)}}" method="POST">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">&times;</button>
                    <a href="{{ url_for('posts.delete', id=post.id)}}" type="button" class="btn btn-danger">Yes,
                        Confirm</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

blog/templates/blog/home.html
{% extends 'base.html' %}

{% block content %}
<div class="row my-2">
    <div class="col-md-8">
        {% for post in posts.items %}
        <ul class="list-unstyled grid">
            <div>
                <img src="{{ url_for('static', filename='images/' + post.author.image)}}" class="img"
                    alt="{{ post.title }}">
            </div>
            <div class="items mx-1 mt-2">
                <li>Author: <a href="{{url_for('posts.user_posts', username=post.author.username)}}">{{
                        post.author.username}}</a></li>
                <li>Date Posted: {{ post.date_created.strftime('%Y-%m-%d') }}</li>
                <a href="{{ url_for('posts.detail', id=post.id)}}">
                    <h6>{{ post.title }}</h6>
                </a>
                <p style="font-size: 14px">{{ post.content }}</p>
            </div>
        </ul>
        {% endfor %}
    </div>
</div>
<div class="row ms-5 mb-2">
    <div class="col-md-6">
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
        {% if posts.page == page_num %}
        <a class="btn btn-primary mb-2" href="{{url_for('main.home', page=page_num)}}">{{ page_num}}</a>
        {% else %}
        <a class="btn btn-outline-primary mb-2" href="{{url_for('main.home', page=page_num)}}">{{ page_num}}</a>
        {% endif %}
        {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock content %}

blog/templates/blog/user_posts.html
{% extends 'base.html' %}

{% block content %}
<div class="row my-2">

    <div class="col-md-8">
        <h4 class="ps-5 py-2" style="font-family: 'Courier New', Courier, monospace;">Posted by {{
            user.username }} ({{ posts.total }}) Posts</h4>
        {% for post in posts.items %}
        <ul class="list-unstyled grid">
            <div>
                <img src="{{ url_for('static', filename='images/' + post.author.image)}}" class="img"
                    alt="{{ post.title }}">
            </div>
            <div class="items mx-1 mt-2">
                <li>Author: {{ post.author.username}}</li>
                <li>Date Posted: {{ post.date_created.strftime('%Y-%m-%d') }}</li>
                <a href="{{ url_for('posts.detail', id=post.id)}}">
                    <h6>{{ post.title }}</h6>
                </a>
                <p style="font-size: 14px">{{ post.content }}</p>
            </div>
        </ul>
        {% endfor %}
    </div>
</div>
<div class="row ms-5 mb-2">
    <div class="col-md-6">
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
        <!-- {% if page_num.next_num %}
        <a href="{{url_for('user_posts', username=user.username, page=page_num)}}">previous</a>
        {% endif %} -->
        {% if posts.page == page_num %}
        <a class="btn btn-primary mb-2" href="{{url_for('posts.user_posts', username=user.username, page=page_num)}}">{{
            page_num}}</a>
        {% else %}
        <a class="btn btn-outline-primary mb-2"
            href="{{url_for('posts.user_posts',username=user.username, page=page_num)}}">{{ page_num}}</a>
        {% endif %}

        {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock content %}